title: "C言語とOpenGLで作るゲームエンジン開発(2Dレンダリング編 - Step1)"
summary: "本Bookでは、実行基盤とメモリ管理レイヤの初期化を行なっていきます。"
topics: ["c", "opengl", "glfw", "gameengine", "graphics"]
published: true
price: 0
chapters:
  - step1_0_introduction
  - step1_1_application_base
  - step1_2_application_layer
  - step1_3_base_layer
  - step1_4_core_memory_linear_allocator
  - step1_5_core_memory_system
  - step1_6_doxygen
